# Generated by Django 2.2 on 2019-12-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
