# Generated by Django 2.2 on 2020-04-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('MP', 'Madhya Pradesh'), ('A', 'Assam'), ('B', 'Bihar'), ('CG', 'Chhattisgarh'), ('G', 'Goa'), ('GJ', 'Gujarat'), ('H', 'Haryana')], max_length=2),
        ),
    ]
